dist: bionic

language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - MAGENTO_INSTALL_EDITION=ce
    - MAGENTO_BASE_URL=magento.test
    - MAGENTO_CONTAINER_NAME=magento
    - MAGENTO_INSTALL_DIR=/var/www/dist
  jobs:
    - MAGENTO_INSTALL_VERSION=2.2.9 MAGENTO_IMAGE_NAME=techdivision/magento2-${MAGENTO_INSTALL_EDITION}:${MAGENTO_INSTALL_VERSION}
    - MAGENTO_INSTALL_VERSION=2.3.2 MAGENTO_IMAGE_NAME=techdivision/magento2-${MAGENTO_INSTALL_EDITION}:${MAGENTO_INSTALL_VERSION}
    - MAGENTO_INSTALL_VERSION=2.3.3 MAGENTO_IMAGE_NAME=techdivision/magento2-${MAGENTO_INSTALL_EDITION}:${MAGENTO_INSTALL_VERSION}

addons:
  hosts:
    - magento.test

sudo: required

services:
  - docker

before_install:
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - composer selfupdate

script:
  - docker run --rm -d --name ${MAGENTO_CONTAINER_NAME} -p 127.0.0.1:80:80 -p 127.0.0.1:443:443 -p 127.0.0.1:3306:3306 -e MAGENTO_BASE_URL=${MAGENTO_BASE_URL} ${MAGENTO_IMAGE_NAME}
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction --optimize-autoloader
  - vendor/bin/robo prepare:docker ${MAGENTO_BASE_URL} ${MAGENTO_CONTAINER_NAME}
  - vendor/bin/robo run:tests-acceptance ${MAGENTO_INSTALL_EDITION} ${MAGENTO_INSTALL_VERSION}
  - vendor/bin/robo run:tests-integration
  - vendor/bin/robo build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: t.wagner@techdivision.com
  