language: php

php:
  - 7.1
  - 7.2

sudo: required

services:
  - docker

before_install:
  - pecl install xdebug-2.6.0
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - composer selfupdate

script:
  - composer update
  - vendor/bin/robo run:tests-integration
  - vendor/bin/robo build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: t.wagner@techdivision.com

env:
  global:
  - secure: WvTVJLIIVsQV0kG98EvMGibrTXOzkVSziVjRPADNAZLYmrcPoxLH7jnhJOTB02JIga78Q+Mk5GeWJi9vKNwzntY2iYPgzL4idt5AKxMIQW8ur0aJdLWAMUjEnYeVY3tF9UU0WS2JJXn3xT8oqKrbGheNG54mjdJNdZfE3YPSJd9q73seP9VYUWLR3rsJernQgeEO8NlB/nY0j0B5gLaeeJZtOjwhSddpyB5VdudyGkTEVZyWv0/9waE1JkUmIxQd2jb6oCTGo9h9+bWwWxCs+fC2LIulHdsB35ECNMZYvl/uch0ZL4XvAP3RtQExBqdNKBklb4J1UJbRgDkvhOxa58b2wPwDBuxN6ki/+UgXPJZ5nO6IgIZ8aXRYWR9TGKCR2YDNAa6ReSeQFUnjLvZHA7o8VcUVjs5MoF6AdpKvlangmLIqupgzQKKs5Me07Chi6lfepa4192J/lTnxI7Lns6WuaGDEPIG9n4EIVt7hOkbYX2ZILl8LDiwTkrsY2bJXGgOiB2mWN1RCK4VsaGORvhrAIW75nLeGw0iLFIPvd8ej7ulRDZ13b1sNCp0VEZXzXzAeX0FEkWokh2eO1YuPj+DgCLNlAYxahPQMzLTd/ATRz54L1L596lYPG6gK3EYIdh6dE05kf9lXQ3UQEJLbYpsodWne0sdV19fAmDPT9X0=
  - secure: Vtg5vBpO2mpN7t4pWGHZnHvvj7J1wdlzrqg2wyqiM1vPq86ax/UvGsn/iHocoyAW3CH3iysNsk04il1wElEwpaEOkti7DDqbTtCpPLXa617xRerI9uId/A3Kam6YzVFbLAjrxZht/lmKEIM+3C23NRS8yc/tWpnr5rkBk7ZP6yEEOLZoLWyp5Z+mdGVBLDvwCptinYDPeXgQtFAzindQYcJYQi1z5ZSDyx6NLtUgfbTSKgvkB+JjcyBbT6ByTnPXJNYvJXa4qXv7/zcSfa0WHJ+eSy199RHpUIcOHPp/N6h5zh3ThY69OJ2hYtVg5dcHt8+QuWMPvwGkE061gIy2hOUMEzIZZY4gV3apeadMB2HWCvZeYAhKjWBxJ7eSn5/S0FILQ51v7K/ofaLinMOzeTAaRuDkvEnkHn+y0H4txbvcIWMNzyFN0HjPBBMzJwN357azpFRdve1E8c3m5eT5Yz+EyQxbM0SOd7hEaMMHrqG5XZ8i02Ql4gxb5r9vWRsoSrNZgbpRXy0IPaKbyz2ANklZ/xoewe7TG199jUWyuH/qL4l65Ki6uKg6huc5bgsyfLLBrgG9e5dQ8DOjEiCBBPtAvilsZqKbUga++dXaEvcwFH00bMZbX90AE4lPaDaczXN2MJunPrBP7KepjjUqcZKqxSwDD+4aD9zwJVrGvnA=
