language: php

php:
  - 7.0
  - 5.6

sudo: required

services:
  - docker

before_install:
  - pecl install xdebug-2.5.5
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - composer selfupdate

script:
  - composer update
  - vendor/bin/robo run:tests-integration
  - vendor/bin/robo build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: t.wagner@techdivision.com