default:
  extensions:
    Behat\Symfony2Extension:
      kernel:
        class: TechDivision\Import\Cli\Simple\AppKernel
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      sessions:
        default:
          goutte: ~
        production:
          chrome:
            api_url: http://localhost:9222
  suites:
    attribute_set:
     paths:
       features: features/attribute-set
     contexts:
       - AttributeSetFeatureContext: ~
       - ConsoleContext: ~
    attribute:
     paths:
       features: features/attribute
     contexts:
       - AttributeFeatureContext: ~
       - ConsoleContext: ~
    category:
     paths:
       features: features/category
     contexts:
       - CategoryFeatureContext: ~
       - ConsoleContext: ~
    product:
     paths:
       features: features/product
     contexts:
       - AttributeSetFeatureContext: ~
       - AttributeFeatureContext: ~
       - CategoryFeatureContext: ~
       - ProductFeatureContext: ~
       - FeatureContext: ~
       - ConsoleContext: ~
  