default:
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      base_url: http://magento-ce-233.test
      sessions:
        default:
          goutte: ~
        production:
          chrome:
            api_url: http://localhost:9222
  suites:
    attribute_set:
     paths:
       features: features/attribute-set
     contexts:
       - AttributeSetFeatureContext:
           installDir: instances/ce/2.3.3
    attribute:
     paths:
       features: features/attribute
     contexts:
       - AttributeFeatureContext:
           installDir: instances/ce/2.3.3
    category:
     paths:
       features: features/category
     contexts:
       - CategoryFeatureContext:
           installDir: instances/ce/2.3.3
    product:
     paths:
       features: features/product
     contexts:
       - ProductFeatureContext:
           installDir: instances/ce/2.3.3