framework:
    secret: test_blah
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: false
    validation: false
    default_locale: en
    session: ~

parameters:
    install_dir: "%env(INSTALL_DIR)%"
    base_url: "%env(BASE_URL)%"